
// table:status_codes
// 予約種別 st_reserve_class
const STATUS_QEEG_FIRST_VISIT = 20;
const STATUS_QEEG_PAID_FREE = 21;
const STATUS_QEEG_ONLINE = 22;
const STATUS_PSYCHIATRY = 23;
const STATUS_TMS = 24;
const STATUS_TMS_FIRST_VISIT = 22;
const STATUS_CONSULTATION = 26;
const STATUS_DUMMY_CARD = 27;

//初診／再診
const REGULARLY_FIRST = 88;
const REGULARLY_RE = 99;

//流入元
const STATUS_OTHER = 77;
const STATUS_COUBIC = 44;
const STATUS_RECEPTION = 55;

// 権限
const ROLE_SYSTEM_ADMINISTRATOR = 35;
const ROLE_CALLCENTER_FULL_ACCESS = 36;
const ROLE_READ_ONLY_ACCESS = 37;
const ROLE_CALLCENTER_ACCESS = 38;
const ROLE_CLINIC_FULL_ACCESS = 39;
